### ISSUE TITLE
Had hard time getting Geckodriver to work

### ISSUE THREAD

**Issue by Dankni95** [sdaqo/anipy-cli#3]
Hi,

I installed geckodriver with pacman, but it still gave me an error about path. Tried setting path manually in .bashrc with no luck.

What fixed my problem was using ```pip install webdriver-manager```

And this code in url.py:
```
from selenium import webdriver
from webdriver_manager.firefox import GeckoDriverManager

                browser = webdriver.Firefox(
                    executable_path=GeckoDriverManager().install())

```

Maybe this can be helpful to someone! :)

**Comment by sdaqo** [comment]
Hi, I know what problem you are running into, its because of a stupid commit a did yesterday. Basically I wanted it to be more convenient so you dont have to have geckodriver in the PATH, but just in the folder of the installation. Seems like its just confusing. Well I changed it back now, so anyone running into issues please do `git pull` and if you are on linux you can just do `sudo make all`. 
So regarding your solution, I have to look into it but it seems like a good solution to me, I didn't know something like this exsisted.
